; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

;; is this one needed?
[env:nucleo_l432kc]
platform = ststm32
board = nucleo_l432kc
framework = cmsis


[env:sm]
platform = ststm32
board = nucleo_l432kc
framework = cmsis
src_filter = +<sm/>

[env:dsp]
platform = ststm32
board = nucleo_l432kc
framework = cmsis
src_filter = +<dsp/>


[env:shared]
platform = ststm32
board = nucleo_l432kc
framework = cmsis
src_filter = +<shared/>